"
Look only on lateral packages and not in the current one.
"
Class {
	#name : 'CoUnitLateralPackageSelectorFetcher',
	#superclass : 'CoLocalLateralPackageSelectorFetcher',
	#category : 'ExtendedHeuristicCompletion-Dependency-Messages',
	#package : 'ExtendedHeuristicCompletion-Dependency-Messages'
}

{ #category : 'accessing' }
CoUnitLateralPackageSelectorFetcher >> packageLocalSelectors: aBlock [

	
]
